# Stage 1 - Build Stage
FROM node:23 AS builder

# Install build dependencies
WORKDIR /app
COPY package*.json ./
RUN npm install

# Copy source code and Prisma files
COPY . .

# Build the NestJS application
RUN npm run build


# Stage 2 - Production Stage
FROM node:23

# Set working directory
WORKDIR /app

# Copy only the built app and necessary files
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

# Install only production dependencies
RUN npm install --production

# Install ts-node for running TypeScript seeders
RUN npm install ts-node --save-dev
RUN npm install --save-dev @types/bcrypt
RUN npm install --save-dev @types/amqplib